/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTimerRouteImport } from './routes/_authenticated/timer'
import { Route as AuthenticatedPsikotesRouteImport } from './routes/_authenticated/psikotes'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedLatihanSoalRouteImport } from './routes/_authenticated/latihan-soal'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatbotRouteImport } from './routes/_authenticated/chatbot'
import { Route as AuthenticatedForumIndexRouteImport } from './routes/_authenticated/forum.index'
import { Route as AuthenticatedCatatanIndexRouteImport } from './routes/_authenticated/catatan.index'
import { Route as AuthenticatedForumIdRouteImport } from './routes/_authenticated/forum.$id'
import { Route as AuthenticatedCatatanIdRouteImport } from './routes/_authenticated/catatan.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTimerRoute = AuthenticatedTimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPsikotesRoute = AuthenticatedPsikotesRouteImport.update({
  id: '/psikotes',
  path: '/psikotes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLatihanSoalRoute =
  AuthenticatedLatihanSoalRouteImport.update({
    id: '/latihan-soal',
    path: '/latihan-soal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatbotRoute = AuthenticatedChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedForumIndexRoute = AuthenticatedForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatatanIndexRoute =
  AuthenticatedCatatanIndexRouteImport.update({
    id: '/catatan/',
    path: '/catatan/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedForumIdRoute = AuthenticatedForumIdRouteImport.update({
  id: '/forum/$id',
  path: '/forum/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatatanIdRoute = AuthenticatedCatatanIdRouteImport.update({
  id: '/catatan/$id',
  path: '/catatan/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chatbot': typeof AuthenticatedChatbotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/latihan-soal': typeof AuthenticatedLatihanSoalRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/psikotes': typeof AuthenticatedPsikotesRoute
  '/timer': typeof AuthenticatedTimerRoute
  '/catatan/$id': typeof AuthenticatedCatatanIdRoute
  '/forum/$id': typeof AuthenticatedForumIdRoute
  '/catatan/': typeof AuthenticatedCatatanIndexRoute
  '/forum/': typeof AuthenticatedForumIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chatbot': typeof AuthenticatedChatbotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/latihan-soal': typeof AuthenticatedLatihanSoalRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/psikotes': typeof AuthenticatedPsikotesRoute
  '/timer': typeof AuthenticatedTimerRoute
  '/catatan/$id': typeof AuthenticatedCatatanIdRoute
  '/forum/$id': typeof AuthenticatedForumIdRoute
  '/catatan': typeof AuthenticatedCatatanIndexRoute
  '/forum': typeof AuthenticatedForumIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/chatbot': typeof AuthenticatedChatbotRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/latihan-soal': typeof AuthenticatedLatihanSoalRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/psikotes': typeof AuthenticatedPsikotesRoute
  '/_authenticated/timer': typeof AuthenticatedTimerRoute
  '/_authenticated/catatan/$id': typeof AuthenticatedCatatanIdRoute
  '/_authenticated/forum/$id': typeof AuthenticatedForumIdRoute
  '/_authenticated/catatan/': typeof AuthenticatedCatatanIndexRoute
  '/_authenticated/forum/': typeof AuthenticatedForumIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chatbot'
    | '/dashboard'
    | '/latihan-soal'
    | '/leaderboard'
    | '/psikotes'
    | '/timer'
    | '/catatan/$id'
    | '/forum/$id'
    | '/catatan/'
    | '/forum/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chatbot'
    | '/dashboard'
    | '/latihan-soal'
    | '/leaderboard'
    | '/psikotes'
    | '/timer'
    | '/catatan/$id'
    | '/forum/$id'
    | '/catatan'
    | '/forum'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/chatbot'
    | '/_authenticated/dashboard'
    | '/_authenticated/latihan-soal'
    | '/_authenticated/leaderboard'
    | '/_authenticated/psikotes'
    | '/_authenticated/timer'
    | '/_authenticated/catatan/$id'
    | '/_authenticated/forum/$id'
    | '/_authenticated/catatan/'
    | '/_authenticated/forum/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/timer': {
      id: '/_authenticated/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof AuthenticatedTimerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/psikotes': {
      id: '/_authenticated/psikotes'
      path: '/psikotes'
      fullPath: '/psikotes'
      preLoaderRoute: typeof AuthenticatedPsikotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/latihan-soal': {
      id: '/_authenticated/latihan-soal'
      path: '/latihan-soal'
      fullPath: '/latihan-soal'
      preLoaderRoute: typeof AuthenticatedLatihanSoalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chatbot': {
      id: '/_authenticated/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof AuthenticatedChatbotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forum/': {
      id: '/_authenticated/forum/'
      path: '/forum'
      fullPath: '/forum/'
      preLoaderRoute: typeof AuthenticatedForumIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catatan/': {
      id: '/_authenticated/catatan/'
      path: '/catatan'
      fullPath: '/catatan/'
      preLoaderRoute: typeof AuthenticatedCatatanIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forum/$id': {
      id: '/_authenticated/forum/$id'
      path: '/forum/$id'
      fullPath: '/forum/$id'
      preLoaderRoute: typeof AuthenticatedForumIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catatan/$id': {
      id: '/_authenticated/catatan/$id'
      path: '/catatan/$id'
      fullPath: '/catatan/$id'
      preLoaderRoute: typeof AuthenticatedCatatanIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatbotRoute: typeof AuthenticatedChatbotRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLatihanSoalRoute: typeof AuthenticatedLatihanSoalRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedPsikotesRoute: typeof AuthenticatedPsikotesRoute
  AuthenticatedTimerRoute: typeof AuthenticatedTimerRoute
  AuthenticatedCatatanIdRoute: typeof AuthenticatedCatatanIdRoute
  AuthenticatedForumIdRoute: typeof AuthenticatedForumIdRoute
  AuthenticatedCatatanIndexRoute: typeof AuthenticatedCatatanIndexRoute
  AuthenticatedForumIndexRoute: typeof AuthenticatedForumIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatbotRoute: AuthenticatedChatbotRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLatihanSoalRoute: AuthenticatedLatihanSoalRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedPsikotesRoute: AuthenticatedPsikotesRoute,
  AuthenticatedTimerRoute: AuthenticatedTimerRoute,
  AuthenticatedCatatanIdRoute: AuthenticatedCatatanIdRoute,
  AuthenticatedForumIdRoute: AuthenticatedForumIdRoute,
  AuthenticatedCatatanIndexRoute: AuthenticatedCatatanIndexRoute,
  AuthenticatedForumIndexRoute: AuthenticatedForumIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
